### ISSUE TITLE
SocketException: No such host is known

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#219]
I'm getting this error on connect, not sure how to fix it. I'm on Windows 10, .NET 4.6.2, TwitchLib 1.5.2, WebSocketSharp-NonPreRelease 1.0.0.

```
6/24/2017 7:55:49 PM|Fatal|WebSocket.connect:0|System.Net.Sockets.SocketException (0x80004005): No such host is known
        at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
        at WebSocketSharp.WebSocket.setClientStream()
        at WebSocketSharp.WebSocket.doHandshake()
        at WebSocketSharp.WebSocket.connect()
```

**Comment by swiftyspiffy** [comment]
Has the library worked in the past? Recently did this start?

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this. Feel free to reopen as needed.
